alias gs='git status'
alias ga='git add *'
alias gc='git commit -m"$1"'
alias gac='git commit -am"$1"'
alias gl='git pull'
alias gp='git push'
alias chrome='C:\\Program\ Files\ \(x86\)\\Google\\Chrome\\Application\\chrome.exe'
